server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quanlynhansu
    username: postgres
    password: 040505
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
